version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3000"
    environment:
      - NODE_ENV=development
      - DUPLICATE_RNG_INDEX_URL_MAX_ATTEMPT=3
      - INITIAL_MIN_URL_SIZE=3
      - PORT=3000
      - MONGODB_URL_STRING=mongodb://root:example@mongodb:27017/db?authSource=admin
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
      - mongodb-log:/var/log/mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

volumes:
  mongodb-data:
    driver: local
    name: mongo-data
  mongodb-log:
    driver: local
    name: mongo-log